In [3]:
import duckdb
import pandas as pd

In [2]:
sql_query = '''
SHOW TABLES
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4            gold_vehicles_metrics
5           parking_violation_2023
6          parking_violation_codes
7          parking_violations_2023
8                        ref_model
9   silver_parking_violation_codes
10       silver_parking_violations
11        silver_violation_tickets
12       silver_violation_vehicles

In [16]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=TRUE
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violation_2023 AS
SELECT *
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=TRUE
  )
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [17]:
sql_query = '''
SELECT * FROM parking_violation_codes LIMIT 5
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,code,definition,manhattan_96th_st_below,all_other_areas
0,1,FAILURE TO DISPLAY BUS PERMIT,515,515
1,2,NO OPERATOR NAM/ADD/PH DISPLAY,515,515
2,3,UNAUTHORIZED PASSENGER PICK-UP,515,515
3,4,BUS PARKING IN LOWER MANHATTAN,115,115
4,5,BUS LANE VIOLATION,250,250

In [ ]:
sql_query = '''
SELECT * FROM ref_model
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   count_star()
0            97

In [4]:
sql_query = '''
SHOW TABLES
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4            gold_vehicles_metrics
5           parking_violation_2023
6          parking_violation_codes
7          parking_violations_2023
8                        ref_model
9   silver_parking_violation_codes
10       silver_parking_violations
11        silver_violation_tickets
12       silver_violation_vehicles

In [5]:
sql_query = '''
SELECT * FROM bronze_parking_violations LIMIT 5
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,summons_number,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,vehicle_expiration_date,violation_location,violation_precinct,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,vehicle_color,vehicle_year
0,9010912681,CA,PAS,2022-10-11,17,SUBN,FORD,T,20220788,50.0,50,50,365910,T201,D,0825A,BX,NaN,BLACK,0
1,4858762841,NY,PAS,2023-08-21,36,4DSD,HONDA,V,0,NaN,0,0,0,None,None,1036A,BK,True,GY,2003
2,4854645684,FL,PAS,2023-07-26,36,UT,BMW,V,0,NaN,0,0,0,None,None,0126P,QN,True,WHI,2022
3,9044582707,NY,PAS,2023-04-10,21,SUBN,SUBAR,T,20231217,79.0,79,79,370326,T301,H,0924A,K,NaN,GY,2017
4,9041503330,NY,PAS,2023-03-21,21,4DSD,CHEVR,T,20250320,26.0,26,26,373097,T103,C,1155A,NY,NaN,BK,2018

In [19]:
sql_query = '''
show tables
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                              name
0   bronze_parking_violation_codes
1        bronze_parking_violations
2                      first_model
3              gold_ticket_metrics
4            gold_vehicles_metrics
5           parking_violation_2023
6          parking_violation_codes
7          parking_violations_2023
8                        ref_model
9   silver_parking_violation_codes
10       silver_parking_violations
11        silver_violation_tickets
12       silver_violation_vehicles

In [8]:
sql_query = '''
SELECT * FROM silver_parking_violation_codes LIMIT 10
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,violation_code,definition,is_manhattan_96th_st_below,fee_usd
0,1,FAILURE TO DISPLAY BUS PERMIT,False,515
1,1,FAILURE TO DISPLAY BUS PERMIT,True,515
2,2,NO OPERATOR NAM/ADD/PH DISPLAY,False,515
3,2,NO OPERATOR NAM/ADD/PH DISPLAY,True,515
4,3,UNAUTHORIZED PASSENGER PICK-UP,False,515
5,3,UNAUTHORIZED PASSENGER PICK-UP,True,515
6,4,BUS PARKING IN LOWER MANHATTAN,False,115
7,4,BUS PARKING IN LOWER MANHATTAN,True,115
8,5,BUS LANE VIOLATION,False,250
9,5,BUS LANE VIOLATION,True,250

In [10]:
sql_query = '''
SELECT * FROM silver_violation_tickets LIMIT 10
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

,summons_number,issue_date,violation_code,is_manhattan_96th_st_below,issuing_agency,violation_location,violation_precinct,issuer_precinct,issuer_code,issuer_command,issuer_squad,violation_time,violation_county,violation_legal_code,fee_usd
0,9010912681,2022-10-11,17,False,T,50.0,50,50,365910,T201,D,0825A,BX,NaN,95
1,4858762841,2023-08-21,36,False,V,NaN,0,0,0,None,None,1036A,BK,True,50
2,4854645684,2023-07-26,36,False,V,NaN,0,0,0,None,None,0126P,QN,True,50
3,9044582707,2023-04-10,21,False,T,79.0,79,79,370326,T301,H,0924A,K,NaN,65
4,9041503330,2023-03-21,21,False,T,26.0,26,26,373097,T103,C,1155A,NY,NaN,65
5,8964996320,2023-06-12,21,False,T,46.0,46,46,374612,T201,E,0923A,BX,NaN,65
6,9019285804,2022-11-20,40,False,T,20.0,20,20,357701,T103,P,0230P,NY,NaN,115
7,9000744076,2022-07-19,69,False,T,6.0,6,6,373104,T102,I,0349P,NY,NaN,35
8,4839205334,2023-04-30,36,False,V,NaN,0,0,0,None,None,1154A,BK,True,50
9,9006263692,2022-09-20,16,False,T,84.0,84,84,368636,T301,P,0308P,K,NaN,95

In [11]:
sql_query = '''
SELECT * FROM gold_ticket_metrics
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

    violation_code  ticket_count  total_revenue_usd
0               36         37064          1853200.0
1                5          3477           869250.0
2               21         12149           789685.0
3               14          5047           580405.0
4               40          3902           448730.0
..             ...           ...                ...
71              23             1               60.0
72              41            18                0.0
73               0            14                NaN
74              94             1                NaN
75              95             4                NaN

[76 rows x 3 columns]

In [13]:
sql_query = '''
SELECT * FROM gold_vehicles_metrics
'''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   registration_state  ticket_count
0                  NJ          9258
1                  PA          3514
2                  FL          2414
3                  CT          1787
4                  GA           840
..                ...           ...
57                 AB             1
58                 BC             1
59                 NB             1
60                 PE             1
61                 SK             1

[62 rows x 2 columns]

In [14]:
sql_query = '''
SELECT
    violation_code,
    SUM(fee_usd) AS total_revenue_usd
FROM
    silver_parking_violation_codes
GROUP BY
    violation_code
HAVING
    NOT(total_revenue_usd >= 1)
    '''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   violation_code  total_revenue_usd
0              41                0.0

In [15]:
sql_query = ''' 
select * from "nyc_parking_violations"."main_dbt_test__audit"."violation_codes_revenue"
    '''

with duckdb.connect('data/nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

   violation_code  total_revenue_usd
0              41                0.0

In [18]:
sql_query_import_1 = '''
CREATE OR REPLACE TABLE parking_violation_codes AS
SELECT *
FROM read_csv_auto(
  'data/dof_parking_violation_codes.csv',
  normalize_names=TRUE
  )
'''

sql_query_import_2 = '''
CREATE OR REPLACE TABLE parking_violation_2023 AS
SELECT *
FROM read_csv_auto(
  'data/parking_violations_issued_fiscal_year_2023_sample.csv',
  normalize_names=TRUE
  )
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
  con.sql(sql_query_import_1)
  con.sql(sql_query_import_2)

In [20]:
sql_query = '''
show tables
'''

with duckdb.connect('data/prod_nyc_parking_violations.db') as con:
    display(con.sql(sql_query).df())

                             name
0  bronze_parking_violation_codes
1       bronze_parking_violations
2             gold_ticket_metrics
3           gold_vehicles_metrics
4          parking_violation_2023
5         parking_violation_codes
6        silver_violation_tickets
7       silver_violation_vehicles